---

- hosts: all
  become: true
  tasks:

  - name: install the apache2 and php packages for Ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install the apache2 and php packages for Centos
    dnf: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"