
- name: install the apache2 and php packages
  tags: apache,httpd,php
  package: 
    name: 
      - ""{{ apache_package_name }}""
      - ""{{ php_package_name }}""
    state: latest


- name: start httpd (centos)
  tags: apache,centos,httpd
  service:
    name: ""{{ apache_service }}""
    state: started
    enabled: yes

- name: change email adress in cfg file
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf 
    regeexp: '^ServerAdmin'
    line: ServerAdmin admin@gmail.com
  when: ansible_distribution == "CentOS"
  notify: restart_apache



- name: copy default html file to site
  tags: apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
