- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    scr: https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_386.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root